# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='is_favorite',
            new_name='favorite',
        ),
    ]
